version: "3.7"
services:
  dashboard:
    build:
      target: dashboard
      context: ./dashboard
    volumes:
      - data:/data/
    restart: unless-stopped
  gosst-http:
    build:
      target: gosst-http
      context: ./gosst
    volumes:
      - data:/data/
    restart: unless-stopped
  gosst-tcp:
    build:
      target: gosst-tcp
      context: ./gosst
    ports:
      - "557:557"
    volumes:
      - data:/data/
    restart: unless-stopped
  caddy:
    image: caddy:2.7.5
    restart: unless-stopped
    depends_on:
      - dashboard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - data:/data/
volumes:
  data: